### ISSUE TITLE
Use provisioning backend for dashboards, providers

### ISSUE THREAD

**Issue by ofbeaton** [voxpupuli/puppet-grafana#103]
It would be great if the puppet types had a switch so they used the new grafana 5.x provisioning backend. It solves a lot of problems that those two types can have using the API, especially dashboards (duplicate dashboards, dashboard not found, dashboard contents changed error).

http://docs.grafana.org/administration/provisioning/

For now I am just using the file {} types w/ templates to do it, which honestly works well enough, but the puppet type could generate the .yaml file for you.

It would be a good workaround for #35 and #47 .

**Comment by bastelfreak** [comment]
Hi @ofbeaton, thanks for the hint! Can you provide a PR that documents this? Maybe with some examples?

**Comment by petems** [comment]
I'm looking into some of this after running into issues trying to provision dashboards from JSON files and getting weird 500 errors, let me see if I can PR it 👍
