### ISSUE TITLE
puppet-grafana Debian repository should use codename stretch

### ISSUE THREAD

**Issue by drshawnkwang** [voxpupuli/puppet-grafana#112]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.3
- Ruby: 2.9.4
- Distribution: Deiban Stretch
- Module version: 4.2.0

## How to reproduce (e.g Puppet code you use)
Simply run and the code and install grafana, specifically the grafana repository list.

## What are you seeing
File '/etc/apt/sources.list.d/grafana.list' contains line
`deb https://packagecloud.io/grafana/stable/debian jessie main`

## What behaviour did you expect instead
File should contain line
`deb https://packagecloud.io/grafana/stable/debian stretch main`

## Output log
n/a

## Any additional information you'd like to impart
Grafana upstream documentation says to use release codename 'stretch'. http://docs.grafana.org/installation/debian/

This is very similar to PR #41.

**Comment by bastelfreak** [comment]
Hi @drshawnkwang, thanks for bringing this up. Are you able to provide a PR for this?

**Comment by drshawnkwang** [comment]
I created a branch and tested it on Debian 9 stretch, but did not do so on any other system. If I created the PR, could someone test it on other OSes to verify that changing the release doesn't break anything else.

**Comment by bastelfreak** [comment]
Just open up the PR, we can write an acceptance test for it.

**Comment by drshawnkwang** [comment]
Sure
