### ISSUE TITLE
Cannot create users as Admin

### ISSUE THREAD

**Issue by OnesAndTwos** [voxpupuli/puppet-grafana#121]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.2
- Ruby: 2.5.1
- Distribution:
- Module version: 4.4.1

## How to reproduce (e.g Puppet code you use)

```
$admin_map = {
    $admin_user => {
      theme            => 'light',
      grafana_url      => 'http://localhost:3000',
      grafana_user     => 'bob',
      grafana_password => 'bobobobobobob',
      is_admin         => true,
      password         => 'bob,
      email            => "bob@localhost"
    }
  }
create_resources('grafana_user', $admin_map)

```

## What are you seeing

A user who is not an admin even though it is specified in the type

## What behaviour did you expect instead

A user who is an admin

## Any additional information you'd like to impart

The code in `lib/puppet/provider/grafana_user/grafana.rb` creates a user if it doesn't exist and sets password and permissions if it does exist. In the create call it uses `isGrafanaAdmin` which I think is an unsupported parameter to a POST. It therefore beomces impossible to create an admin user.

OR I have made a huge misunderstanding

**Comment by OnesAndTwos** [comment]
I think it is definitely a problem so forking to fix. Will try to give a merge request in the future when I look a bit deeper into your submission guidelines :)

**Comment by bastelfreak** [comment]
Hey @OnesAndTwos, thanks for opening up this issue. We're always happy to provide guidance for people contributing code or working with git. Just ping us on https://puppetcommunity.slack.com or on our IRC channel #voxpupuli on freenode.
