### ISSUE TITLE
multi arch send out a notice

### ISSUE THREAD

**Issue by elfranne** [voxpupuli/puppet-grafana#152]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.0.4
- Ruby:  2.5.3p105
- Distribution: Ubuntu/Debian
- Module version: master branch

If you have enable i386 arch enabled you get a notice when running apt-get update:

N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://packages.grafana.com/oss/deb stable InRelease' doesn't support architecture 'i386'

By default apt::source will try to get all the enabled architectures unless you specify the available architectures on the repo.

As far as i can tell, only amd64 and arm architectures are available on the repo.

Should i make a PR to list the available arch on the repo ?

**Comment by bastelfreak** [comment]
Hi @elfranne, can you please provide a PR?
