### ISSUE TITLE
Missing dependency to APT module ?

### ISSUE THREAD

**Issue by mfaure** [voxpupuli/puppet-grafana#174]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: v6.4.2
- Ruby: 
- Distribution: Ubuntu 18.04
- Module version: 6.0.0

## How to reproduce (e.g Puppet code you use)

```
  $_grafana_port = 3000

  class { 'grafana':
    cfg => {
      app_mode => 'production',
      server   => {
        http_port => $_grafana_port,
      },
      users    => {
        allow_sign_up => false,
      },
    },
  }
```

## What are you seeing

When deploying on a host, I've got the following error:

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::apt for XXX.taqamaqa.com (file: /etc/puppetlabs/code/environments/production/modules/grafana/manifests/install.pp, line: 74, column: 15) on node XXX.taqamaqa.com
> Warning: Not using cache on failed catalog
> Error: Could not retrieve catalog; skipping run

It seems a dependency to [apt module](https://forge.puppet.com/puppetlabs/apt/) is not declared.

## What behaviour did you expect instead

Having Grafana installed :)

## Any additional information you'd like to impart

Adding `mod 'puppetlabs-apt', '7.0.1'` to my Puppetfile fixed the issue

/label:bug

**Comment by ghoneycutt** [comment]
This is a soft dependency since it is only needed if running on a platform that uses Apt. The requirement is already documented, though the versioning is off as it says you need v4. Instead of the metadata.json, could you please update the README.md.

**Comment by mfaure** [comment]
Ah, interesting the concept of soft dependency, thank you. I did not see the requirement part of the doc, my bad. Actual doc looks good to me, so this is not a bug. Sorry for the inconvenience and thank you for the explanations :)
