### ISSUE TITLE
Cannot install puppet/grafana, most recent puppet/archive version is v4.2

### ISSUE THREAD

**Issue by rfoster-ucd** [voxpupuli/puppet-grafana#184]
Attempting to install puppet/grafana on Puppet Server v6. Install fails on dependency check for puppet/archive (>= 1.0.1 < 4.0.0) when latest is v4.2.0.

> $ sudo /opt/puppetlabs/bin/puppet module install puppet-grafana --version 6.0.0
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not install module 'puppet-grafana' (???)
  No version of 'puppet-grafana' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module

**Comment by mfaure** [comment]
This have been fixed in 01eb3f5741ee9a36ac414694a12b8db3e5d2384d and it should be shipped in next release I think

**Comment by Dan33l** [comment]
Closed by #176
