### ISSUE TITLE
Setting provisioning_dashboards will purge path even if puppetsource is not set

### ISSUE THREAD

**Issue by yoshz** [voxpupuli/puppet-grafana#186]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)

I manage the dashboard provider path with vcsrepo instead of using the puppetsource option. 

## What are you seeing

After the repository is cloned but afterwards all files and directories in this path are deleted.

## What behaviour did you expect instead

No files or directories should be deleted. 

## Any additional information you'd like to impart

See the PR for a fix.

**Comment by root-expert** [comment]
Implemented in #225
