### ISSUE TITLE
Code in maifests/service.pp refers to code from manifests/params.pp

### ISSUE THREAD

**Issue by cavandavid** [voxpupuli/puppet-grafana#206]
**BUG**
I can see the old params.pp has been removed now, but there's still code that refers to it.

https://github.com/voxpupuli/puppet-grafana/blob/master/manifests/service.pp#L14

Evaluation Error: Unknown variable: 'grafana::params::docker_image'. (file: /etc/puppetlabs/code/envs/cavan/modules/upstream/grafana/manifests/service.pp, line: 14, column: 21) on node

**Comment by dhoppe** [comment]
Good catch. Are you able to provide a pull request?
