### ISSUE TITLE
Remove docker dependency

### ISSUE THREAD

**Issue by ardichoke** [voxpupuli/puppet-grafana#22]
Since the docker install is purely optional, it doesn't make sense to require that the docker module be installed. It should be removed from dependencies and the documentation should be updated to state that it needs to be installed if you wish to use docker support. This actually prevents my organization from using this module, as we use a different docker module and the conflict causes install of the module to fail.

**Comment by wyardley** [comment]
I agree, and style guide does too.
#61 switches it to a soft dependency.
