### ISSUE TITLE
'uid' property is not included in datasource provisioning

### ISSUE THREAD

**Issue by luukspierings** [voxpupuli/puppet-grafana#229]
## Affected Puppet, Ruby, OS and module versions/distributions
latest

## How to reproduce (e.g Puppet code you use)
```
-> grafana_datasource { 'Jaeger':
    uid          => 'jaeger'
    grafana_url       => $grafana_url,
    grafana_user      => $admin_user,
    grafana_password  => $admin_pw,
    type              => 'jaeger',
    url               => $jaeger_endpoint,
    access_mode       => 'proxy',
}
```
## What are you seeing
Not the right uid being configured in Grafana for that datasource.

## What behaviour did you expect instead
The datasource being provisioned with the right uid

## Any additional information you'd like to impart
The Grafana documentation for provisioning a datasource includes a 'uid' property to be configured:
https://grafana.com/docs/grafana/latest/administration/provisioning/

The `grafana_datasource` resource is currently not open for configuring that 'uid' property, could that be added?

**Comment by joernott** [comment]
This becomes more and more urgent with grafana 9.0, as the dashboard json no longer contains a property like
```
"datasource": "datasource_name",
```
but instead something like
```
"datasource": {
  "type": "influxdb",
  "uid": "FaB6S62nk"
},
```
As grafana keeps adding the datasource to ervery graph, this now requires a lot of editing of the exported json tom replace the old code with the new one, as grafana tends to add the dashboards default data source to every single query now. And recently (9.0.7) grafana became quite creative in replacing the string with an array like
```
"datasource": [
 1: "d",
 2: "a",
 3: "t",
...
],
```

So, being able to set the uid explicitly and later reference that UID in a dashboard would make things a lot easier
