### ISSUE TITLE
Configured grafana debian repo should contain current distribution

### ISSUE THREAD

**Issue by varac** [voxpupuli/puppet-grafana#27]
Currently for debian, ["wheezy" is hardcoded](https://github.com/voxpupuli/puppet-grafana/blob/master/manifests/install.pp#L78) as distribution.
It should pick up the current distribution

```
root@mail:/etc# cat /etc/apt/sources.list.d/grafana.list 
# This file is managed by Puppet. DO NOT EDIT.
# grafana
deb https://packagecloud.io/grafana/stable/debian wheezy main

root@mail:/etc# facter os
{"name"=>"Debian", "family"=>"Debian", "release"=>{"major"=>"8", "minor"=>"7", "full"=>"8.7"}, "lsb"=>{"distcodename"=>"jessie", "distid"=>"Debian", "distdescription"=>"Debian GNU/Linux 8.7 (jessie)", "distrelease"=>"8.7", "majdistrelease"=>"8", "minordistrelease"=>"7"}}
```

**Comment by bastelfreak** [comment]
Hi @varac, thanks for the issue. Are you able to provide a pull request with the needed changes?

**Comment by dhoppe** [comment]
This [line](https://github.com/voxpupuli/puppet-grafana/blob/master/manifests/install.pp#L78) is responsibe, but I think we schould cleanup the code and only support installations via packagecloud.io to get rid of the archive resource.
