### ISSUE TITLE
Invalid port variable for LDAP configuration

### ISSUE THREAD

**Issue by soerenbe** [voxpupuli/puppet-grafana#29]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Agent 3.7.2, Server 3.4.3
- Ruby: Agent: 2.1.5p273 (system package) Server: 1.9.3p484 (system package)
- Distribution: Agent: Jessie, Server: Trusty
- Module version: 2.6.3
- toml version: toml-0.1.2

## How to reproduce (e.g Puppet code you use)

```puppet
  class { 'grafana':
    manage_package_repo => false,
    install_method      => 'repo',
    version             => '4.1.2-1487860575',
    cfg                 => {
      security  => {
        admin_user     => 'admin',
        admin_password => 'xxx',
        secret_key     => 'xxx',
      },
      snapshots  => {
        external_enabled => false,
      },
      users      => {
        allow_sign_up    => false,
        allow_org_create => false,
      },
      analytics   => {
        reporting_enabled => false,
      },
      smtp        => {
        enabled      => true,
        host         => 'localhost:25',
        from_address => "admin@${::fqdn}",
        from_name    => 'Dashboard Admin'
      },
      'auth.ldap' => {
        enabled     => true,
        config_file => '/etc/grafana/ldap.toml',
      },
    },
    ldap_cfg => {
      servers => [
        { host            => 'xxx',
          use_ssl         => true,
          search_filter   => '(sAMAccountName=%s)',
          search_base_dns => [ 'xxx' ],
          bind_dn         => 'xxx',
          bind_password   => 'xxx',
          port            => 3269,
        },
      ],
      'servers.attributes' => {
        name      => 'givenName',
        surname   => 'sn',
        username  => 'sAMAccountName',
        member_of => 'memberOf',
        email     => 'mail',
      },
      'servers.group_mappings' => [
        { group_dn => 'xxx',
          org_role => 'Viewers',
        },
        ]
    },
  }
```
## What are you seeing

When depolying this configuration the module produce a invalid `port` entry in /etc/grafana/ldap.toml. 

```
# cat /etc/grafana/ldap.toml | grep port
port = "3269"
```

With this configuration grafana-server refuses to start.

```
Mär 01 17:40:59 dashboard grafana-server[62396]: t=2017-03-01T17:40:59+0100 lvl=crit msg="Failed to load ldap config file" logger=ldap error="Type mismatch for 'login.LdapConfig.servers': Type mismatch for 'login.LdapServerConf.port': Expected integer but found 'string'."
```

## What behaviour did you expect instead

Following configuration would work:
```
# cat /etc/grafana/ldap.toml | grep port
port = 3269
```

## Any additional information you'd like to impart
Since I am not very good at ruby and this TOML is magic for me I can not post a pull request. This also could be a TOML problem and not related to this module.

Best Regards,
Sören

**Comment by ffrank** [comment]
Thanks for this report!

**Comment by furhouse** [comment]
@soerenbe I just used your config as example, and if you would append `+0` to 3269 (so `port => 3269+0,` as mentioned in the README (Integer note), it produces the expected result, and grafana-server will start just fine.

**Comment by soerenbe** [comment]
Thanks for this hint!
I wil try this. At least I can use the configuration and dont have to manage the configuration file by hand.

But it is still a bug. :)

**Comment by ffrank** [comment]
Aye. Will tackle this once I've got some time on my hands.

**Comment by dhoppe** [comment]
I think we should get rid of tool, because the project has not seen any commit for more than one year.

**Comment by alexjfisher** [comment]
The workaround in the README, did work, but was only required up until Puppet 4.  Since we dropped support for Puppet 3 a _long_ time ago, the workaround in the README was removed in https://github.com/voxpupuli/puppet-grafana/pull/281
