### ISSUE TITLE
grafana_teams undefined method `match' for nil:NilClass

### ISSUE THREAD

**Issue by mplaats** [voxpupuli/puppet-grafana#318]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet 7.x
- Ruby: 2.7
- Distribution: debian 11
- Module version: 11.2.0

## How to reproduce (e.g Puppet code you use)

  grafana_team { 'developpers':
  ensure                => 'present',
  grafana_url           => 'http://localhost:3000',
  grafana_user          => 'admin',
  grafana_password      => '*****',
  home_dashboard        => 'RABBITMQ Stats per vhost/queue',
  home_dashboard_folder => 'Rabbitmq Statistieken',
  organization          => '********',
  }

## What are you seeing

I see the first run doing well, it creates the team and all is fine. Second run it produces an error.

## What behaviour did you expect instead

No error, and if team exist it skippes.

## Output log

Error: /Stage[main]/Rabbitmq_grafana/Grafana_team[developpers]: Could not evaluate: undefined method `match' for nil:NilClass

## Any additional information you'd like to impart

I was using grafana version 9.x. Bumping back to 8.x the problem is solved.

**Comment by aro-lew** [comment]
same problem here

-  Puppet: Puppet v7.24.0
-  Ruby: 2.5
-  Distribution: debian 11
-  Module version: 11.2.0

is there a workaround or an quick fix?

**Comment by mplaats** [comment]
I downgraded grafana to version 8 for now, so the request should be to update the module to version 9.
