### ISSUE TITLE
Configure grafana with grafana::cfg doesn't work

### ISSUE THREAD

**Issue by recid** [voxpupuli/puppet-grafana#353]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.22
- Ruby: 2.7.4p191
- Distribution: Debian
- Module version: 7.0.0

## How to reproduce (e.g Puppet code you use)
I used 2 methods : 
* hiera style
```grafana::cfg:
  app_mode: 'production'
  database:
    type: 'postgres'
    host: 'pgsql.test.local:5432'
    name: 'grafana_db'
    user: 'grafana_user'
    password: 'grafana'
  server:
    http_port: 80
  users:
    allow_sign_up: true
    skip_org_role_sync: true
```
* puppet style
```
    class { 'grafana':
      cfg => {
        app_mode => 'production',
        database => {
          type => 'postgres',
          host => 'pgsql.test.local:5432',
          name => 'grafana_db',
          user => 'grafana_user',
          password  => 'grafana',
        },
        server   => {
          http_port     => 80,
        },
        users    => {
          allow_sign_up         => true,
          skip_org_role_sync => true,
        },
      },
    }
```
## What are you seeing
* With hiera style, none of my `grafana::cfg` variables are setup into the grafana.ini file
* With puppet style, I get an error because the grafana class doesn't have a `cfg` parameter

## What behaviour did you expect instead
Regardless of the method used, my grafana.ini should contain the defined variables

## Output log
* With hiera
cf [hiera_output.log](https://github.com/voxpupuli/puppet-grafana/files/14964479/hiera_output.log)

* With puppet
```
Info: Loading facts
Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Grafana]: has no parameter named 'cfg' (file: /tmp/puppet/modules/extends_grafana/manifests/init.pp, line: 19, column: 5) on node infra-grafana-001.test.local
```

## Any additional information you'd like to impart
* Into the hiera style, we can see that the module reset the initial `grafana.ini` file and change the permissions/owner with root and 0744. Whereas into the `grafana::config` class, normally we should have 0644 for the user/group `grafana`
* Into puppet style, the `grafana` class has a cfg parameter. So I don't understand why I got that error 
```
class grafana (
  Optional[String] $archive_source,
  String $cfg_location,
  Hash $cfg,
....
```

Furthermore, I test other modules versions : 10.0.1, 12.0.0 and 13.1.0. I got the same error.

Last information, I want to use the hiera style (instead of puppet style) because I can configure my grafana instance without create a puppet module

Thanks in advance for your help

**Comment by n1nj444** [comment]
Hi,

I got the same issue, can you please check ?

**Comment by recid** [comment]
Finally It works. 
My bad because I got an older puppet grafana module which conflicts with this module
