### ISSUE TITLE
Usable for Grafana 4.x?

### ISSUE THREAD

**Issue by linuxmail** [voxpupuli/puppet-grafana#37]
hi,

just a short question. Is this module usable for Grafana 4.x too?

Big thank for the work :-)

**Comment by bastelfreak** [comment]
I'm using it on archlinux. I'm pretty sure you want to use it on another distribution. Would you mind testing it and report feedback?

**Comment by dhoppe** [comment]
@linuxmail We just released a new version of this module and changed the default installation method from ```package``` to ```repo```. Unfortunately I forgot to set the version to ```undef```. This means it would still try to install version 2.5.0, even if 4.2.0 is the current version. It gets worse, if you make an upgrade via ```apt-get``` and Puppet makes and downgrade.

**Comment by linuxmail** [comment]
hi,

I can say: no problem. I already saw the variable and overwritten it before the first Puppet run. So it works without any issues :-)

very big thanks.
