### ISSUE TITLE
Feature request: support auth.proxy config option

### ISSUE THREAD

**Issue by linuxmail** [voxpupuli/puppet-grafana#40]
Hello,

it would be great, if it is possible to activate the [auth.proxy](https://grafana-net.raintank.io/blog/2015/12/07/grafana-authproxy-have-it-your-way/) config option, for SSO/CAS requirements.:

```
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true
```

or 

```
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = email
auto_sign_up = true
```

which requires:

```
[users]
allow_sign_up = true
auto_assign_org = true
auto_assign_org_role = Editor
```

**Comment by dhoppe** [comment]
@linuxmail This module already supports the configuration above. You just need to provide the correct values to the `cfg` hash.

**Comment by dhoppe** [comment]
@linuxmail Did you solve your problem or do you have further questions?

**Comment by dhoppe** [comment]
The following code is just working fine:
```
class { 'grafana':
  cfg => {
    users        => {
      allow_sign_up        => true,
      auto_assign_org      => true,
      auto_assign_org_role => 'Editor',
    },
    'auth.proxy' => {
      enabled         => true,
      header_name     => 'X-WEBAUTH-USER',
      header_property => 'username',
      auto_sign_up    => true,
    },
  },
}
```

**Comment by SHMarcoG** [comment]
Hi,
Do you know if this is also possible in Hiera?
