### ISSUE TITLE
using docker install with container_cfg attempts to use incorrect permissions

### ISSUE THREAD

**Issue by Justin-DynamicD** [voxpupuli/puppet-grafana#52]
Including a sample class:

`if $grafana_install {
    class { 'grafana':
      install_method  => 'docker',
      container_cfg   => true,
      container_params => {
        'ports' => "${grafana_port}:${grafana_port}"
      },
      cfg => {
        app_mode => 'production',
        server   => {
          http_port => $grafana_port,
        },
        'auth.anonymous'     => {
          enabled   => true,
        },
      },
    }`

In the above scenario, the module will erroneously attempt to set ownership to the grafana.ini file to "grafana:grafana" even though the user will not exist on the host (it's in a docker container).

I can temporarily get around this by just creating the user, but I shouldn't need to.

**Comment by dhoppe** [comment]
@Justin-DynamicD I think this issue can be closed, because Grafana now creates the user and the group with the help of the Dockerfile:
* https://github.com/grafana/grafana-docker/commit/e2872ea0deac347fd0a9d25baf7c70683aa94a5a
* https://github.com/grafana/grafana/blob/master/Dockerfile#L63-L64
