### ISSUE TITLE
Module doesn't work on Ubuntu Xenial

### ISSUE THREAD

**Issue by jarro2783** [voxpupuli/puppet-grafana#56]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10
- Ruby: 2.3.4
- Distribution: Ubuntu Xenial
- Module version: 3.0.0

## How to reproduce (e.g Puppet code you use)

`include grafana`

## What are you seeing

`apt-get update` fails because there is no package for Xenial on packagecloud. Part of the puppet run is below:
```
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: The repository 'https://packagecloud.io/grafana/stable/debian xenial Release' does not have a Release file.
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: s3://freelancer-packages.s3.amazonaws.com/deb/dists/stable/Release.gpg: Signature by key 8000B5F9FB908ADE43299B588457C3F2BAD4BAD6 uses weak digest algorithm (SHA1)
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: s3://freelancer-packages.s3.amazonaws.com/ubuntu/dists/xenial/Release.gpg: Signature by key 8000B5F9FB908ADE43299B588457C3F2BAD4BAD6 uses weak digest algorithm (SHA1)
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: Failed to fetch https://packagecloud.io/grafana/stable/debian/dists/xenial/main/binary-amd64/Packages  404  Not Found
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: Some index files failed to download. They have been ignored, or old ones used instead.
Error: /Stage[main]/Apt::Update/Exec[apt_update]: Failed to call refresh: '/usr/bin/apt-get update' returned 100 instead of one of [0]
Error: /Stage[main]/Apt::Update/Exec[apt_update]: '/usr/bin/apt-get update' returned 100 instead of one of [0]
```

## What behaviour did you expect instead

I expect this to have installed correctly.

**Comment by wyardley** [comment]
Can you try w/ #61? We should have a release soon.

**Comment by jarro2783** [comment]
That works, thanks.

**Comment by wyardley** [comment]
@jarro2783 great. The release is on the forge now as well.

**Comment by jarro2783** [comment]
Thanks, but I still don't see a release on the forge.

The latest version here is still 3.0.0: https://forge.puppet.com/puppet/grafana

**Comment by wyardley** [comment]
Yes, you're right, I realized right after I wrote you that the deploy failed :/

We'll be releasing 4.0.1 as soon as it's merged.
