### ISSUE TITLE
Create organization 

### ISSUE THREAD

**Issue by tpoindessous** [voxpupuli/puppet-grafana#71]
Hi

It would be great if we could have a class for creating organization.

Thanks !

**Comment by bastelfreak** [comment]
Hi @tpoindessous, thanks for this feature request. Are you able to provide a patch for this?

**Comment by tpoindessous** [comment]
I can try ;)

**Comment by brandonrdn** [comment]
@bastelfreak this was added in PR #86. Should be able to close this.
