### ISSUE TITLE
Getting rid or changing the url check for grafana datasource url's

### ISSUE THREAD

**Issue by Faffnir** [voxpupuli/puppet-grafana#75]
Currently every datasource is checked if it is starting with http(s) which leads to an error in the newest version of grafana (4.6.0) which supports postgresql as a datasource.
With this [check](https://github.com/voxpupuli/puppet-grafana/blob/f505078e1fc09a55328d08e8bf9446a42e1c0f88/lib/puppet/type/grafana_datasource.rb#L35) it is impossible to set a valid postgresql datasource.

Valid solutions would be to remove this check or check the datasource type before.
What do you think?

**Comment by actatux** [comment]
Hi @Faffnir,

Thank you for reporting this issue.
Indeed the url parameter must be `host:port` for both mysql and postgres datasources.

I will give a try with the check of the datasource type.

**Comment by actatux** [comment]
By looking at the granafa code, DataSource.Url is a `string`. I can't find any test nor documentation about a formal format for this string, thus we can expect other format than `https?://www.example.com` or `host:port` in the future.

@Faffnir , can you submit a PR with your change?

**Comment by actatux** [comment]
Fix by #76 
Thank you @Faffnir .

**Comment by actatux** [comment]
Fix by #76 
Thank you @Faffnir .

**Comment by actatux** [comment]
Fix by #76 
Thank you @Faffnir .

**Comment by Faffnir** [comment]
thank you for the fast merge @actatux
