### ISSUE TITLE
grafana plugin install/check breaks catalog run when grafana-server service is not running

### ISSUE THREAD

**Issue by jfschneider** [voxpupuli/puppet-grafana#79]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.6 aio
- Ruby: 2.1.9p490
- Distribution: RHEL7
- Module version: 4.0.2
- grafana: grafana-4.5.1-1.x86_64

## How to reproduce (e.g Puppet code you use)
```
include ::grafana
```
```yaml
grafana::plugins:
  'grafana-simple-json-datasource':
    ensure: 'present'
```

## What are you seeing
```
Error: Failed to apply catalog: Execution of '/usr/sbin/grafana-cli plugins ls' returned 1: Error: ✗ error: stat /var/lib/grafana/plugins: no such file or directory

NAME:
   Grafana cli plugins ls - list all installed plugins

USAGE:
   Grafana cli plugins ls [arguments...]
```

## What behaviour did you expect instead
at least this error should not stop the catalog apply

## Output log
see above
## Any additional information you'd like to impart
The problem seems that /var/lib/grafana/plugins is created at first startup of grafana-server, beforehand it does not exist. So there is a dependency
 ```Class['grafana::service'] ->  Grafana_Plugin <| |>```
but that is not possible because of 
```Grafana_Plugin <| |> ~> Class['grafana::service']```
in init.pp

**Comment by byblakout** [comment]
+1

**Comment by onstring** [comment]
+1 
meet with exactly the same issue.  does anyone have a good solution for this?
